version: '3.8'

services:
  app:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 in the container to port 3000 on the host
    environment:
      - NODE_ENV=production
    # Optionally, you can add other configuration options like volumes, depends_on, etc.



